GET http://localhost:5000/api/auth/users HTTP/1.1

###
GET http://localhost:5000/api/auth/register HTTP/1.1

###
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{ 
  "firstName": "Iyobosa", 
  "lastName": "Omoruyi",
  "email": "omoruyiiyobosa@yahoo.com",
  "password": "rrcwg3335555"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{ 
  "email": "omosiyobo@gmail.com",
  "password": "admin123"
}

###
GET http://localhost:5000/api/auth?Authorization=BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjJlZWNhZGM3ZmQ1NTE4ODJiMzIzZWFmIn0sImlhdCI6MTY1OTgzMDY1OCwiZXhwIjoxNjYwMTkwNjU4fQ.l9QDOvYeL4m-35wNrbPuMuJZfZCPlQTfC6z_bOPAfgY

###
GET http://localhost:5000/api/auth/logout HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:5000/api/auth/reset
Content-Type: application/json

{ 
  "firstName": "Iyobosa", 
  "lastName": "Omoruyi",
  "email": "omoruyiiyobosa@yahoo.com"
}

###
GET http://localhost:5000/api/auth/admin HTTP/1.1
Content-Type: application/json

{ 
  "email": "omosiyobo@gmail.com",
  "password": "admin123"
}