GET http://localhost:5000/api/auth/users HTTP/1.1

###
GET http://localhost:5000/api/auth/register HTTP/1.1

###
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{ 
  "firstName": "Iyobosa", 
  "lastName": "Omoruyi",
  "email": "kkjkjbk445h@yahoo.com",
  "password": "rrch7t5555"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{ 
  "email": "kkjklhhlh@yahoo.com",
  "password": "rrcwg3335555"
}

###
GET http://localhost:5000/api/auth

###
GET http://localhost:5000/api/auth/logout HTTP/1.1


###
PUT http://localhost:5000/api/auth/reset
Content-Type: application/json

{ 
  "firstName": "Iyobosa", 
  "lastName": "Omoruyi",
  "email": "omoruyiiyobosa@yahoo.com"
}

###
POST http://localhost:5000/api/auth/admin HTTP/1.1
x-access-token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjJlZjljYjMwY2M5MmQ4OTg5Y2YyNTRjIn0sImlhdCI6MTY1OTg3NDkyOSwiZXhwIjoxNjYwMjM0OTI5fQ.wOJY8hphqdan8MNy07kaNuV2elvSu_5m_EVXswArl18
Content-Type: application/json
